
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/academia
      user: root
      password: 195682
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate.format_sql: true

    logging:
      level:
        org:
          hibernate:
            type: trace

